### ISSUE TITLE
Excessive avoidOffset on Anroid

### ISSUE THREAD

**Issue by hahahatey** [mateusz1913/react-native-avoid-softinput#120]
### Environment

Library version: 2.4.6
OS version: Android 12

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

Hello everyone
I have code structure something like that:
```javascript
useMount(() => {
    AvoidSoftInput.setAdjustNothing();
    return () => {
      AvoidSoftInput.setDefaultAppSoftInputMode();
    };
  });

<SafeAreaView>
      <ScrollView>
        <AvoidSoftInputView avoidOffset={65}>
          <Input
            style={{marginTop: 100, marginHorizontal: 24}}
            placeholder="text"
          />
        </AvoidSoftInputView>
      </ScrollView>
    </SafeAreaView>
```

I expect when input is situated above the opened keyboard and there is no need to push Input above the keyboard  because it`s visible on its own avoidOffset should not be applied.  It works this way on IOS but not Android

https://user-images.githubusercontent.com/41858788/196190187-f7308e21-15be-42e1-8603-c4e0b36a74fb.mov

https://user-images.githubusercontent.com/41858788/196190198-028a5ab2-fe67-4e8c-8492-21fe48592875.mov

### Expected behavior

avoidOffset is applied when input has to be pushed above the keyboard

### Reproduction

-

**Comment by mateusz1913** [comment]
So the issue is on iOS rather than Android, isn't it?

**Comment by hahahatey** [comment]
Well, actually desirable behavior is the way ios works)
I did not managed to find a way to determine whether input will be pushed or not.
I might apply avoidOffset conditionally based on this information.
By the way, thank you for the lib and fast response)

**Comment by mateusz1913** [comment]
I don't agree that it's desirable to push the text field up even if it does not need to be pushed, because if it would be the case, then what if the text field's top edge would touch the top edge of screen or status bar area? It would result in text field being pushed above the visible part of the screen (or under the status bar). Definitely not desirable

In case of iOS it is slightly pushed probably because the screen from recording does not use safeareaview (or does not apply bottom safe area inset).

So if you ask for the change of the behavior, then I can definitely say it won't be done.

However, if you still want to achieve it, you can do it manually - you can listen for keyboard events and when keyboard is displayed, you can apply manually some padding (equal to avoidOffset) to your text field. There is even [`useSoftInputState` hook](https://mateusz1913.github.io/react-native-avoid-softinput/docs/api/hooks/use-soft-input-state) that you can use for reacting to keyboard being open/closed

**Comment by hahahatey** [comment]
No, i did not mean to ask for the change. My question was rather if it`s correct behavior. I got that it is.
Yes, i know about the hook, but it does not solve my problem. As i said  i would like to apply a padding only when an input pushed above the keyboard(it was obscure by keyboard, after the push happens it becomes visible). Otherwise there must not be the padding(input was visible before push and after keyboard opens it stays visible)

**Comment by mateusz1913** [comment]
> As i said i would like to apply a padding only when an input pushed above the keyboard(it was obscure by keyboard, after the push happens it becomes visible). Otherwise there must not be the padding(input was visible before push and after keyboard opens it stays visible)

So I think that's the current behavior library provides. Text field is translated (or the padding to for that text field is applied) only when it would be obscured by the keyboard. And if it wouldn't no translation or padding is applied.

That's the basic case 😄

In a little more complex one, with the scrollview, if the text field would be covered, the library applies padding **to the scrollview** and scrolls to that text field. If the text field wouldn't be covered, padding is still applied to scrollview, so that user can access other elements inside the scrollview that are obscured by the keyboard.

**Comment by hahahatey** [comment]
Thank you for the explanation
I will try to find another way around my problem
Close the issue
