### ISSUE TITLE
what are the shortcomings and when do I need to consider the alternatives

### ISSUE THREAD

**Issue by itsramiel** [mateusz1913/react-native-avoid-softinput#123]
### Feature request

I have been using react-native-keyboard-manager for a good amount of time, but I noticed your package is maintained and supports the new arch, so I wanted to give it a try. 

I noticed the alternatives section, but I was wondering if you could provide a __known issuess__ or __why choose an alternative__ section that would help make a decision when migrating libraries. Maybe a list of known shortcomings or issues would be nice if possible?

**Comment by mateusz1913** [comment]
@itsramiel There's no _known issue/limitation_.
The reason why I decided to make an "Alternatives" section is that "keyboard handling" is not a trivial task that can be always solved with the same library. Each project has its own requirements or constraints and I don't claim this library is a magic wand that will solve them all 😄. Some projects needs to have JS solution, other just needs sth like mentioned `react-native-keyboard-manager` - you install it and forget, because it will handle most cases out of the box.
Also I think it's nice to highlight other possible solutions, because people doesn't seem to know that alternatives exist.

If you think current rationale in docs can be improved, feel free to suggest sth, I will appreciate it 🙂

**Comment by itsramiel** [comment]
Thank you for the answer. I am really just speaking as a dev checking a library. When I saw the alternatives section, I thought to myself "Why would I use an alternative?", "What can other libs do that this does not or vice versa?". It made me wonder. I thought I would share how I felt.
