### ISSUE TITLE
setEnabled(true) is in the StickyFooterExample docs section, but should not be there

### ISSUE THREAD

**Issue by reganloper** [mateusz1913/react-native-avoid-softinput#125]
### Environment

Library version: 3.0.2
OS version: Android Pixel API 31 emulator (Android 12.0) 

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

On the `StickyFooterExample` screen of your example app, I noticed that in your `onFocusEffect` you use `AvoidSoftInput.setShouldMimicIOSBehavior(true);` but not `AvoidSoftInput.setEnabled(true);`.  I wondered when should we be using `setEnabled` versus when should we not in tandem with `setShouldMimicIOSBehavior`?  One thing I found in my own app is that adding the `AvoidSoftInput.setEnabled(true)` line would add a bunch of extra padding below the sticky footer.

### Expected behavior

Expected that we should be using `AvoidSoftInput.setEnabled(true);` in the `StickyFooterExample` app.

### Reproduction

Run your example app with `StickyFooterExample`, but adding the `AvoidSoftInput.setEnabled(true);` line.

Here is what it looks like with adding `AvoidSoftInput.setEnabled(true);` to `onFocusEffect`:

https://user-images.githubusercontent.com/87994672/202042852-d9abe53c-7480-46b9-82ac-43c8965788cf.mov

**Comment by mateusz1913** [comment]
Hi @reganloper , sorry for the delay.

Thx for creating an issue, good catch. [The docs section](https://mateusz1913.github.io/react-native-avoid-softinput/docs/recipes/recipes-sticky-footer) has `AvoidSoftInput.setEnabled(true)` line, but in reality it's not needed.

Why? Because that "sticky footer" case must be handled "manually" without automatic support provided by calling `AvoidSoftInput.setEnabled(true);`. The library is computing how much padding should be added so that **the focused text field** is not covered by displayed keyboard. It does not add any padding if the text field would be located at the top of the screen (because it would **never** be obscured by the keyboard).
In a case when we want to also push some "non-text field" content (like a "submit" button from `StickyFooterExample`), we have to handle it "manually" by applying the height of the keyboard as an additional padding (check out [lines 45-47](https://github.com/mateusz1913/react-native-avoid-softinput/blob/master/packages/app/src/screens/StickyFooterExample.tsx#L45#L47), [lines 18-22](https://github.com/mateusz1913/react-native-avoid-softinput/blob/master/packages/app/src/screens/StickyFooterExample.tsx#L18#L22) & [line 58](https://github.com/mateusz1913/react-native-avoid-softinput/blob/master/packages/app/src/screens/StickyFooterExample.tsx#L58))

I'll fix the docs, so that it doesn't confuse anyone. Thx again for raising it

**Comment by reganloper** [comment]
@mateusz1913 thanks so much for explaining, and for maintaining this library!  Awesome work.
