### ISSUE TITLE
setting setShouldMimicIOSBehavior change the content when showHeader is set false in react-navigation

### ISSUE THREAD

**Issue by pandey21197** [mateusz1913/react-native-avoid-softinput#127]
### Environment

React Native Avoid Softinput: 3.0.2

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

enabling the soft input in android via: setShouldMimicIOSBehavior

The height of the total view inside react navigation. when the showHeader is set false, the height calculated by react native soft input ignore the status bar height in android.

The results:

1. when showHeader set true in react navigation:

<img width="462" alt="Screenshot 2022-11-28 at 1 41 32 AM" src="https://user-images.githubusercontent.com/100587075/204158183-60f1266a-0b5a-4123-8faa-55ce2d421e5f.png">

2. when showHeader set false in react navigation:
<img width="449" alt="Screenshot 2022-11-28 at 1 38 43 AM" src="https://user-images.githubusercontent.com/100587075/204158204-ffe1575e-8c31-4044-b5e0-2304a5705b92.png">

I was able to solve this by adding a view over my react navigation root container of status bar height:

```
 render() {
    return (
      <GestureHandlerRootView style={styles.container}>
        <ErrorBoundary otaStatus={this.state.otaStatus}>
          <Provider store={store}>
            <PersistGate loading={null} persistor={persistor}>
              <SafeAreaView style={styles.headContainer} />
              <SafeAreaView style={styles.mainContainer}>
                <StatusBar
                  backgroundColor={Colors.screenBackground}
                  barStyle={'dark-content'}
                />
                <View style={styles.softInputHeightAndroid}>
                  <FlashMessage />
                  {this.state.deviceInfoLoaded && <RootNavigator />}
                </View>
                <OTAUpdateModal otaStatus={this.state.otaStatus} />
              </SafeAreaView>
            </PersistGate>
          </Provider>
        </ErrorBoundary>
      </GestureHandlerRootView>
    );
  }
}

const styles = StyleSheet.create({
  headContainer: {flex: 0, backgroundColor: theme.palette.pageBackground},
  mainContainer: {flex: 1, backgroundColor: theme.palette.neutral.white},
  container: {
    flex: 1,
  },
  softInputHeightAndroid: {
    flex: 1,
    ...Platform.select({android: {paddingVertical: StatusBar.currentHeight}}),
    backgroundColor: theme.palette.pageBackground,
  },
});

```
post the hack:

<img width="460" alt="Screenshot 2022-11-28 at 1 39 10 AM" src="https://user-images.githubusercontent.com/100587075/204158318-ddf6f59a-034d-47bd-b1f8-34671212b5bc.png">

### Expected behavior

Ideally when react navigation is used with showHeader false, the react native soft input should include the height of status bar.

### Reproduction

//

**Comment by mateusz1913** [comment]
Hello @pandey21197, the case you described will not be handled, because I don't see this as a bug - in fact, that behavior aligns it with the default iOS behavior, where you can render views "under" the status bar (so even the `setShouldMimicIOSBehavior` method's name is correct here).

Why it's rendering "under" the status bar? Because, internally, `setShouldMimicIOSBehavior` method calls Android's `WindowCompat.setDecorFitsSystemWindows(view, false)` (this tells the app to not fit to decor views like status bar or keyboard, but let those decor views to overlay on top of the app's window).

Why your case works when `react-navigation` showHeader prop is set to true? Because the header view detects (internally) if status bar padding should be applied or not.

So why I don't want to do the same detection as `react-navigation` does? 
1. This library does not handle status bars - it handles displaying app's content above the keyboard layout
2. Considering that this library does not render any "header" or "top-positioned" view, it's impossible to handle it correctly for ALL possible apps - by ALL possible I mean apps with or without `react-navigation`, apps with or without handled "safe-area", etc.

What you should do in that case? You should handle rendering the content of your Android app's screens with "safe-area" container (like on iOS) e.g. with `react-native-safe-area-context` - and it's not the hack (like you described), this is how it should actually be handled.
