### ISSUE TITLE
[iOS] All TextInputs are incorrectly avoided when a TextInput with `secureTextEntry` is mounted

### ISSUE THREAD

**Issue by fobos531** [mateusz1913/react-native-avoid-softinput#42]
### Environment

Library version: 2.3.3
OS version: 
15.3.1 - iPhone 8
15.4 - iPhone 12

### Affected platforms

- [ ] Android
- [X] iOS

### Current behavior

Hello, let me first preface this with the fact that this is one of the best keyboard avoiding libraries I have ever used! It handled almost all of my cases beautifully. Thank you for that!

There is one issue I noticed though, and it pertains to the password fields on iOS. The core of the issue is that when you focus a TextInput that has a `secureTextEntry` prop enabled, it doesn't apply the correct padding as it does with regular TextInputs. This may be due to the fact that iOS appends an additional "Passwords" row to the top of the keyboard. I also noticed that the incorrect padding is then applied to *every* TextInput that is in the same parent view/screen as the one that has `secureTextEntry` applied, even though those other TextInputs do NOT have a `secureTextEntry` prop set.

### Expected behavior

The expected behavior is for the padding to be correctly applied even when TextFields with `secureTextEntry` are present.

### Reproduction

Reproduction repo: https://github.com/fobos531/keyboard-avoiding-repro

Summary:

- freshly initialized Expo SDK 44 project
- run with `expo run:ios` on **physical** device (may need to set up code signing beforehand). This issue manifests itself **only** on physical devices, since setting `secureTextEntry` doesn't have any effect on simulators.

In `App.tsx` on L16, a TextInput with `secureTextEntry` is added. If you try to focus any of the textfields, you'll notice that the padding is incorrectly applied to both of them. After removing `secureTextEntry` and fully reloading the app (exit and reopen, not just hot refresh) the padding is now correctly applied. The issue is the same if you try to set `secureTextEntry` on the first   TextInput.

Hope this helps! Let me know if you need anything else.

**Comment by mateusz1913** [comment]
Hi @fobos531 , thx for providing repro. After opening repro app on physical iPhone 12 Pro, I observed following behavior:

(I slightly modify repro - grey background is just full screen `<View />` that wraps absolutely positioned input container.)
```ts
return (
    <View style={{ backgroundColor: 'lightgray', flex: 1, alignSelf: 'stretch' }}>
      <View style={{ bottom: 20, position: "absolute", width: "100%" }}>
        <Text>insetsBottom: {insets.bottom}</Text>
        <TextInput style={{ borderColor: "red", borderWidth: 2, paddingVertical: 10, marginBottom: 10 }} />
        <TextInput style={{ borderColor: "red", borderWidth: 2, paddingVertical: 10 }} secureTextEntry />
        <StatusBar animated barStyle="dark-content" />
      </View>
    </View>
  );
```

| First input | Second input |
| ---------- | ------------- |
| ![IMG_0031](https://user-images.githubusercontent.com/25980166/158887671-ba6e6f74-d2a3-48ca-a2f2-6da44a1bccf5.PNG) | ![IMG_0032](https://user-images.githubusercontent.com/25980166/158887708-85bad7db-031e-4a9d-99bf-d7e5549712d5.PNG) |

Second input screenshot has invisible keyboard, because Apple automatically hides it when there is `secureTextEntry` input visible

If you will compare those screenshots, you can notice that focused input has the same distance from the keyboard's top edge. I also checked how it looks like when none of the inputs are `secureTextEntry`:

| First input | Second input |
| ---------- | ------------- |
| ![IMG_0029](https://user-images.githubusercontent.com/25980166/158887498-7fccc46f-c0a7-4215-a1e5-c14cdbcd1552.PNG) | ![IMG_0030](https://user-images.githubusercontent.com/25980166/158887542-a3f1d413-4016-4f75-be74-ba7d35485537.PNG) |

Even when keyboard is "higher" because of suggestions row, distance from keyboard remains the same for both inputs.

The weird thing for me was that distance from bottom of input and keyboard's top edge was not 0 (it's the default, that can be configured by `setAvoidOffset` method).  Also when focusing second input, there is small white area between grey view and keyboard. And it turns out that the distance is equal to bottom safe area inset (34) returned from `react-native-safe-area-context`.

So I tried to check what happens if I will not use position: 'absolute'.

Following code demonstrates input container positioned relatively:

```ts
return (
    <SafeAreaView edges={['bottom']} style={{ flex: 1, alignItems: "center", alignSelf: 'stretch', backgroundColor: 'lightgray', justifyContent: "center" }}>
      <View style={{ alignSelf: 'stretch', flex: 1 }} />
      <Text>insetsBottom: {insets.bottom}</Text>
      <View style={{ alignSelf: 'stretch' }}>
        <TextInput style={{ borderColor: "red", borderWidth: 2, paddingVertical: 10, marginBottom: 10 }} />
        <TextInput style={{ borderColor: "red", borderWidth: 2, paddingVertical: 10 }} secureTextEntry />
      </View>
      <StatusBar animated barStyle="dark-content" />
    </SafeAreaView>
  );
```

| First input | Second input |
| ---------- | ------------- |
| ![IMG_0033](https://user-images.githubusercontent.com/25980166/158889742-77172afb-5747-4e24-88da-2de3e966d0a9.PNG) | ![IMG_0034](https://user-images.githubusercontent.com/25980166/158889776-bb8ae5a5-1e87-4bb9-9e67-fe056582641e.PNG) |

When I positioned that using flex and additionally wrapped it in `<SafeAreaView />` component, focused input is "touching" keyboard's top edge, which is the expected behavior.

My summary is that I would suggest changing input's container position to relative (with flexDirection: 'column-reverse' or with sibling <View /> with flex: 1), because from native code perspective, there is no way to detect if focused input is positioned absolutely (either directly or by positioning parent container absolutely).

Let me know, if we can close that issue 👋
