### ISSUE TITLE
inconsistent behavior between ios and android ?

### ISSUE THREAD

**Issue by a-eid** [mateusz1913/react-native-avoid-softinput#65]
### Environment

Library version: 2.4.4
OS version:  iPhone 13 ios 15
                      android 10

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

the unfocused screen on android is affected by the keyboard on android but not ios 

https://user-images.githubusercontent.com/19273413/163286962-9e6ea5ae-3b86-4a81-b0ea-1a7e827fbb5d.mp4

https://user-images.githubusercontent.com/19273413/163286998-efe75dca-9c6e-407b-b0d7-f0aa8150412e.mp4

### Expected behavior

the unfocused screen should not be affected by the keyboard.	

### Reproduction

- enable the module on android and ios
- trigger the module with an input on a transparent modal ( native-stack modal screen in my case )

**Comment by mateusz1913** [comment]
Hi @a-eid , could you post a link to reproduction repository? It will significantly help me in reproducing incorrect behavior

**Comment by a-eid** [comment]
@mateusz1913 absolutely 
there you go 

https://github.com/a-eid/soft-input-issue-repro

**Comment by a-eid** [comment]
@mateusz1913 I'd like to ask when you have `setEnabled(true)` and I want the content to move up more, in my case to not cover a certain button, how to achieve that ?

**Comment by mateusz1913** [comment]
If you use AvoidSoftInput module, then you can use `setAvoidOffset` method;
If you use AvoidSoftInputView, you can leverage `avoidOffset` prop

**Comment by a-eid** [comment]
it's not clear when to use 'AvoidSoftInputView` vs `AvoidSoftInput.setEnabled(true)` 
I actually much prefer the `AvoidSoftInputView`, but I've had some issues with it esp on ios 

check this out 


https://user-images.githubusercontent.com/19273413/163650065-7f2de286-27bf-484e-aca9-935491cf614f.mp4

**Comment by a-eid** [comment]
another **inconsistent** behavior is when `setEnable(true)` ios has some extra spacing unlike android.


https://user-images.githubusercontent.com/19273413/163651972-353ab01d-0873-44e3-9d2b-df279fff4e1f.mp4



https://user-images.githubusercontent.com/19273413/163651998-8a88816f-2b4b-47bd-bf43-9afb5adc4803.mp4

**Comment by a-eid** [comment]
I found another inconsistent behavior 

as observed in the videos when you transition from screen to another with auto focus, android does not trigger the keyboard event accurately unlike ios 

https://user-images.githubusercontent.com/19273413/163654389-5a1512a4-e787-4ab5-a963-5689363ab12c.mp4


https://user-images.githubusercontent.com/19273413/163654409-e6b63a18-fcd9-4cd8-9d8f-c5b6f12ce567.mp4


will post a repro branch for this one too as soon as I can.

**Comment by mateusz1913** [comment]
@a-eid I investigated those behaviors, and here is summary:

1) behavior from `main` branch:

When using `AvoidSoftInput` module, on iOS, to detect root view (which will have applied offset) lib uses `RCTPresentedViewController` helper function available from react-native core. This function returns currently presented view controller, which _do not need_ to be react root view - in this case it returns a view container from `react-native-screens` (the one holding "modal" screen). Unfortunately on Android, there is no similar helper function. Instead lib traverses view tree until it finds react root view. Without using reflection tricks, there is no way to find corresponding view container from `react-native-screens`, as it is done on iOS side.

So, in this case, there is nothing that can be done. I would instead recommend to use `AvoidSoftInputView` instead (like it is recommended with regular RN Modals)

2) behavior from `ios-modal` branch:

I replicated that behavior, however it seems to be problem with styling - when I changed the structure to following it worked as expected:

```tsx
function Modal({ navigation }: any) {
  return (
    <View style={{ flex: 1 }}>
      {/** Go back only for debugging purposes */}
      <Text style={{ paddingTop: 50, paddingLeft: 30 }} onPress={() => navigation.goBack()}>Go back</Text>
      {/** Instead of using justifyContent: 'flex-end', just add empty View with flex: 1 */}
      <View style={{ flex: 1 }} />
      <View>
        <AvoidSoftInputView style={{ padding: 20, backgroundColor: "blue" }} avoidOffset={20}>
          <TextInput style={{ backgroundColor: "red", height: 45, paddingHorizontal: 20 }} />
        </AvoidSoftInputView>
      </View>
    </View>
  )
}
```

Instead of using `justifyContent: 'flex-end'` , I just added empty View with flex: 1
Another approach (although I did not test it), would be to use `flexDirection: 'column-reverse'`, if you will only have one child in your `View`

I think, there is nothing, that can be done here.

3) behavior from `extra-view` branch:

Yup, that extra space is equal to bottom value of safe area inset, which is hardcoded when computing applied offset.
However, I don't see any logical reason, why text input would have to be positioned below safe area. Nothing which is meant to receive some user interaction should be positioned below safe area. You should wrap your layout inside `SafeAreaView`, so nothing will be displayed under top or bottom safe area inset.

Nothing to be done here.

4) autoFocus behavior

The issue is that keyboard is dismissed in screen A, but it is opened in screen B at nearly the same time. Because library has "debounce" logic implemented on Android (and it can be removed, for perf reasons), it may ignore second event, because it was called too quickly. 
The workaround here would be to remove `autoFocus` prop and focus that input manually after small delay.

Nothing, that can be done here.
