### ISSUE TITLE
Sticky footer - delayed animation on android

### ISSUE THREAD

**Issue by Gongreg** [mateusz1913/react-native-avoid-softinput#77]
### Environment

Library version: 2.4.4
OS version: POCO X3 PRO, Android 11

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

Currently, on android the Sticky footer example has a noticeable delay between keyboard appearing & button moving above the keyboard.

### Expected behavior

There should be no delay like on ios. (button moving together with keyboard)

### Reproduction

Sticky footer example.

By the way, just wanted to thank you for amazing library, it helped me solve a very big head pain of making android/ios experience consistent with keyboard and react-navigation!

**Comment by mateusz1913** [comment]
Hi @Gongreg , sorry for delay.
I compared behavior on Android & iOS. There is a little difference in favor of iOS, however it's because keyboard events on iOS can be detected fractions of second **_before_** the keyboard is displayed by operating system. On Android, detection takes place, when keyboard is displayed.
Because of that different behavior between operating systems, library has default configuration of show animation delay which on Android is 0ms, and on iOS is 300ms. If you feel that it's still inconsistent, you can play with `AvoidSoftInput.setShowAnimationDelay` and pass value greater than 300 on iOS

**Comment by Gongreg** [comment]
Hey, no worries.
That's what I figured. I was wondering if there is any way to listen for keyboard events before the keyboard is displayed on android, but I guess there isn't. In that case there is nothing to be done here. Thanks!
